### PR TITLE
Huggingface Spaces Web Demo

### PR DESCRIPTION
**Pull request by AK391**
Web Demo on Huggingface Spaces using Gradio

### CODE REVIEW

**Comment by LiJunnan1992** [comment]
Thanks for adding the huggingface demo!

**Comment by LiJunnan1992** [comment]
@AK391 It would be very cool if a VQA demo can also be added to Huggingface Spaces!

**Comment by AK391** [comment]
@LiJunnan1992 Thanks, I have added vqa as a option to the Space
Screen Shot 2022-02-01 at 12 58 31 AM

**Comment by LiJunnan1992** [comment]
Thanks so much!

**Comment by LiJunnan1992** [comment]
Hi @AK391, could you please highlight Salesforce Research in either the title or the first paragraph of the demo? Appreciate it!

**Comment by AK391** [comment]
@LiJunnan1992 Sounds good, updated to add Salesforce Research in the first paragraph (building now). Also, I can help migrate this to the Salesforce org on huggingface https://huggingface.co/Salesforce

**Comment by LiJunnan1992** [comment]
That would be great, thanks!

**Comment by AK391** [comment]
@LiJunnan1992 great, I sent a request to join the org, once added I can move the space under Salesforce

**Comment by AK391** [comment]
@LiJunnan1992 Great, I have updated the demo to support nucleus sampling for caption generation

Screen Shot 2022-02-21 at 10 16 13 AM


also any update on moving to the salesforce org https://huggingface.co/Salesforce, I sent a request but it is still pending

**Comment by LiJunnan1992** [comment]
@AK391 , thanks! I'll check with our team for the request.

Could you also help me add in a function to perform image-text matching? The code is also in the demo notebook.

**Comment by LiJunnan1992** [comment]
@AK391 Your request should be approved now.

**Comment by AK391** [comment]
@LiJunnan1992 thanks, the button is still showing up for me and its greyed out 
Screen Shot 2022-02-21 at 10 27 59 PM

do you see my request when you go to organization settings > members?

**Comment by LiJunnan1992** [comment]
Could you try this link? https://huggingface.co/organizations/Salesforce/share/xqnqFwsLkRzwJcvZSkHfWavZEHvkSoKuqU

**Comment by AK391** [comment]
@LiJunnan1992 thanks, added BLIP to the org, also you can remove the share link now from the github comment as it might allow anyone to send requests to join 

Screen Shot 2022-02-21 at 10 51 15 PM

**Pull request merged**
